# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BPTGoogleMap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BPTGoogleMap
   pod 'Alamofire', '~> 4.8.2'
   pod 'SwiftyJSON', '~> 5.0.0'
   pod 'Firebase'
   pod 'Firebase/Messaging'
   pod 'Firebase/Core'
   pod 'Firebase/Auth'
   pod 'Firebase/Storage'
   pod 'Firebase/Database'
   pod 'Fabric', '~> 1.9.0'
   pod 'Crashlytics', '~> 3.12.0'
   pod 'GoogleMaps', '~> 3.8.0'
   pod 'GooglePlaces', '~> 3.8.0'
   pod 'GeoFire'

  target 'BPTGoogleMapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BPTGoogleMapUITests' do
    # Pods for testing
  end

end
